[package]
name = "tauri-plugin-callstyle"
version = "0.1.0"
description = "Нативне сповіщення CallStyle про вхідний дзвінок на Android"
authors = ["dialer"]
edition = "2021"
links = "tauri-plugin-callstyle"

[dependencies]
tauri = { version = "2" }

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
